//cookie
export const RECEIVE_COOKIE = 'RECEIVE_COOKIE';

//plan

export const AVAILABLE_PLANS_REQUEST = 'AVAILABLE_PLANS_REQUEST';
export const AVAILABLE_PLANS_SUCCESS = 'AVAILABLE_PLANS_SUCCESS';
export const AVAILABLE_PLANS_FAILURE = 'AVAILABLE_PLANS_FAILURE';

export const JOINED_PLANS_REQUEST = 'GET_PLAN_REQUEST';
export const JOINED_PLANS_SUCCESS = 'JOINED_PLANS_SUCCESS';
export const JOINED_PLANS_FAILURE = 'JOINED_PLANS_FAILURE';

export const GET_PLAN_REQUEST = 'GET_PLAN_REQUEST';
export const GET_PLAN_SUCCESS = 'GET_PLAN_SUCCESS';
export const GET_PLAN_FAILURE = 'GET_PLAN_FAILURE';
//order

export const UPLOAD_PHOTOS_REQUEST = 'UPLOAD_PHOTOS_REQUEST';
export const UPLOAD_PHOTOS_SUCCESS = 'UPLOAD_PHOTOS_SUCCESS';
export const UPLOAD_PHOTOS_FAILURE = 'UPLOAD_PHOTOS_FAILURE';

export const ALERT_NOTE_REQUEST = 'ALERT_NOTE_REQUEST';
export const ALERT_NOTE_SUCCESS = 'ALERT_NOTE_SUCCESS';
export const ALERT_NOTE_FAILURE = 'ALERT_NOTE_FAILURE';

export const ALERT_REALPLACE_REQUEST = 'ALERT_REALPLACE_REQUEST';
export const ALERT_REALPLACE_SUCCESS = 'ALERT_REALPLACE_SUCCESS';
export const ALERT_REALPLACE_FAILURE = 'ALERT_REALPLACE_FAILURE';

export const ALERT_RESULT_REQUEST = 'ALERT_RESULT_REQUEST';
export const ALERT_RESULT_SUCCESS = 'ALERT_RESULT_SUCCESS';
export const ALERT_RESULT_FAILURE = 'ALERT_RESULT_FAILURE';

export const ALERT_VALIDATE_REQUEST = 'ALERT_VALIDATE_REQUEST';
export const ALERT_VALIDATE_SUCCESS = 'ALERT_VALIDATE_SUCCESS';
export const ALERT_VALIDATE_FAILURE = 'ALERT_VALIDATE_FAILURE';

export const GET_UNDERWRITE_REQUEST = 'GET_UNDERWRITE_REQUEST';
export const GET_UNDERWRITE_SUCCESS = 'GET_UNDERWRITE_SUCCESS';
export const GET_UNDERWRITE_FAILURE = 'GET_UNDERWRITE_FAILURE';

export const CREATE_UNDERWRITE_REQUEST = 'CREATE_UNDERWRITE_REQUEST';
export const CREATE_UNDERWRITE_SUCCESS = 'CREATE_UNDERWRITE_SUCCESS';
export const CREATE_UNDERWRITE_FAILURE = 'CREATE_UNDERWRITE_FAILURE';

export const SET_ORDER_ID = 'SET_ORDER_ID';

export const ALL_ORDER_REQUEST = 'ALL_ORDER_REQUEST';
export const ALL_ORDER_SUCCESS = 'ALL_ORDER_SUCCESS';
export const ALL_ORDER_FAILURE = 'ALL_ORDER_FAILURE';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILURE = 'GET_ORDER_FAILURE';

export const DRIVER_ORDER_REQUEST = 'DRIVER_ORDER_REQUEST';
export const DRIVER_ORDER_SUCCESS = 'DRIVER_ORDER_SUCCESS';
export const DRIVER_ORDER_FAILURE = 'DRIVER_ORDER_FAILURE';

export const DRIVER_ORDERS_REQUEST = 'DRIVER_ORDERS_REQUEST';
export const DRIVER_ORDERS_SUCCESS = 'DRIVER_ORDERS_SUCCESS';
export const DRIVER_ORDERS_FAILURE = 'DRIVER_ORDERS_FAILURE';

export const PLAN_ORDER_REQUEST = 'PLAN_ORDER_REQUEST';
export const PLAN_ORDER_SUCCESS = 'PLAN_ORDER_SUCCESS';
export const PLAN_ORDER_FAILURE = 'PLAN_ORDER_FAILURE';

export const PLAN_ORDERS_REQUEST = 'PLAN_ORDERS_REQUEST';
export const PLAN_ORDERS_SUCCESS = 'PLAN_ORDERS_SUCCESS';
export const PLAN_ORDERS_FAILURE = 'PLAN_ORDERS_FAILURE';

export const SALE_ORDER_REQUEST = 'SALE_ORDER_REQUEST';
export const SALE_ORDER_SUCCESS = 'SALE_ORDER_SUCCESS';
export const SALE_ORDER_FAILURE = 'SALE_ORDER_FAILURE';

export const SALE_ORDERS_REQUEST = 'SALE_ORDERS_REQUEST';
export const SALE_ORDERS_SUCCESS = 'SALE_ORDERS_SUCCESS';
export const SALE_ORDERS_FAILURE = 'SALE_ORDERS_FAILURE';

export const ANDRIVER_ORDER_REQUEST = 'ANDRIVER_ORDER_REQUEST';
export const ANDRIVER_ORDER_SUCCESS = 'ANDRIVER_ORDER_SUCCESS';
export const ANDRIVER_ORDER_FAILURE = 'ANDRIVER_ORDER_FAILURE';

export const ANPLAN_ORDER_REQUEST = 'ANPLAN_ORDER_REQUEST';
export const ANPLAN_ORDER_SUCCESS = 'ANPLAN_ORDER_SUCCESS';
export const ANPLAN_ORDER_FAILURE = 'ANPLAN_ORDER_FAILURE';

export const ANSALE_ORDER_REQUEST = 'ANSALE_ORDER_REQUEST';
export const ANSALE_ORDER_SUCCESS = 'ANSALE_ORDER_SUCCESS';
export const ANSALE_ORDER_FAILURE = 'ANSALE_ORDER_FAILURE';

//vehicle

export const SET_VEHICLE_ID = 'SET_VEHICLE_ID';

export const VEHICLE_MODELS2_REQUEST = 'VEHICLE_MODELS2_REQUEST';
export const VEHICLE_MODELS2_SUCCESS = 'VEHICLE_MODELS2_SUCCESS';
export const VEHICLE_MODELS2_FAILURE = 'VEHICLE_MODELS2_FAILURE';

export const VEHICLE_VEHICLE_REQUEST = 'VEHICLE_VEHICLE_REQUEST';
export const VEHICLE_VEHICLE_SUCCESS = 'VEHICLE_VEHICLE_SUCCESS';
export const VEHICLE_VEHICLE_FAILURE = 'VEHICLE_VEHICLE_FAILURE';

export const INFOS_VEHICLE_REQUEST = 'INFOS_VEHICLE_REQUEST';
export const INFOS_VEHICLE_SUCCESS = 'INFOS_VEHICLE_SUCCESS';
export const INFOS_VEHICLE_FAILURE = 'INFOS_VEHICLE_FAILURE';
//获取报价提交表单(新车已上牌)
export const SET_VEHICLE_INFO_REQUSET = 'SET_VEHICLE_INFO_REQUSET';
export const SET_VEHICLE_INFO_SUCCESS = 'SET_VEHICLE_INFO_SUCCESS';
export const SET_VEHICLE_INFO_FAILURE = 'SET_VEHICLE_INFO_FAILURE';
//获取报价提交表单(新车未上牌)
export const SET_VEHICLE_REQUSET = 'SET_VEHICLE_REQUSET';
export const SET_VEHICLE_SUCCESS = 'SET_VEHICLE_SUCCESS';
export const SET_VEHICLE_FAILURE = 'SET_VEHICLE_FAILURE';
//提交驾驶人信息
export const SET_DRIVER_INFO_REQUSET = 'SET_DRIVER_INFO_REQUSET';
export const SET_DRIVER_INFO_SUCCESS = 'SET_DRIVER_INFO_SUCCESS';
export const SET_DRIVER_INFO_FAILURE = 'SET_DRIVER_INFO_FAILURE';
//修改驾驶人信息
export const CHANGE_DRIVER_INFO_REQUSET = 'CHANGE_DRIVER_INFO_REQUSET';
export const CHANGE_DRIVER_INFO_SUCCESS = 'CHANGE_DRIVER_INFO_SUCCESS';
export const CHANGE_DRIVER_INFO_FAILURE = 'CHANGE_DRIVER_INFO_FAILURE';
//获取某个车的信息
export const GET_VEHICLE_INFO_REQUSET = 'GET_VEHICLE_INFO_REQUSET'
export const GET_VEHICLE_INFO_SUCCESS = 'GET_VEHICLE_INFO_SUCCESS'
export const GET_VEHICLE_INFO_FAILURE = 'GET_VEHICLE_INFO_FAILURE'
//上传图片
export const UPLOAD_IMAGE_REQUSET = 'UPLOAD_IMAGE_REQUSET'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'
//暂存数据使用
export const ADD_DRIVER_VEHICLE = 'ADD_DRIVER_VEHICLE';

export const ADD_DRIVER = 'ADD_DRIVER';

//测试
export const STATE_CHECKED='STATE_CHECKED';

//profile

export const USER_INFORMATION_REQUEST = 'USER_INFORMATION_REQUEST';
export const USER_INFORMATION_SUCCESS = 'USER_INFORMATION_SUCCESS';
export const USER_INFORMATION_FAILURE = 'USER_INFORMATION_FAILURE';

export const GET_USEROPENID_REQUEST = 'GET_USEROPENID_REQUEST';
export const GET_USEROPENID_SUCCESS = 'GET_USEROPENID_SUCCESS';
export const GET_USEROPENID_FAILURE = 'GET_USEROPENID_FAILURE';


//quotation

export const SET_QUOTATION_ID = 'SET_QUOTATION_ID';

export const GET_QUOTATION_REQUEST = 'GET_QUOTATION_REQUEST';
export const GET_QUOTATION_SUCCESS = 'GET_QUOTATION_SUCCESS';
export const GET_QUOTATION_FAILURE = 'GET_QUOTATION_FAILURE';

export const GET_QUOTATIONS_REQUEST = 'GET_QUOTATIONS_REQUEST';
export const GET_QUOTATIONS_SUCCESS = 'GET_QUOTATIONS_SUCCESS';
export const GET_QUOTATIONS_FAILURE = 'GET_QUOTATIONS_FAILURE';

export const GET_QUOTATED_REQUEST = 'GET_QUOTATED_REQUEST';
export const GET_QUOTATED_SUCCESS = 'GET_QUOTATED_SUCCESS';
export const GET_QUOTATED_FAILURE = 'GET_QUOTATED_FAILURE';

export const GET_UNQUOTATED_REQUEST = 'GET_UNQUOTATED_REQUEST';
export const GET_UNQUOTATED_SUCCESS = 'GET_UNQUOTATED_SUCCESS';
export const GET_UNQUOTATED_FAILURE = 'GET_UNQUOTATED_FAILURE';

export const GET_ALLQUOTATIONS_REQUEST = 'GET_ALLQUOTATIONS_REQUEST';
export const GET_ALLQUOTATIONS_SUCCESS = 'GET_ALLQUOTATIONS_SUCCESS';
export const GET_ALLQUOTATIONS_FAILURE = 'GET_ALLQUOTATIONS_FAILURE';

export const ADD_QUOTATION_GROUPS = 'ADD_QUOTATION_GROUPS';
export const INSERT_QUOTATION_SUCCESS = 'INSERT_QUOTATION_SUCCESS';
export const INSERT_QUOTATION_FAILURE = 'INSERT_QUOTATION_FAILURE';

export const MEGATRON_REQUEST = 'MEGATRON_REQUEST';
export const MEGATRON_SUCCESS = 'MEGATRON_SUCCESS';
export const MEGATRON_FAILURE = 'MEGATRON_FAILURE';

//storeMaxScore
export const STORE_MAX_SCORE = 'STORE_MAX_SCORE';
export const STORE_MAX_SCORE2 = 'STORE_MAX_SCORE2'

//storeCondition
export const STORE_QUOTATION_CONDITION = 'STORE_QUOTATION_CONDITION';
export const STORE_ORDER_CONDITION = 'STORE_ORDER_CONDITION';